// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/DataAggregation/js/UI/templates/Coordinates.html":'\x3cdiv class\x3d"pad-left-10"\x3e\r\n  \x3ctable class\x3d"page-table" cellpading\x3d"0"\x3e\r\n    \x3ctbody\x3e\r\n      \x3ctr class\x3d"task-instruction-row"\x3e\r\n        \x3ctd colspan\x3d"2"\x3e\r\n          \x3cdiv class\x3d"instruction pad-bottom-10 bottom-border"\x3e${nls.coordinates.coordinatesPageHint}\x3c/div\x3e\r\n        \x3c/td\x3e\r\n      \x3c/tr\x3e\r\n\r\n      \x3ctr class\x3d"bottom-border"\x3e\r\n        \x3ctd class\x3d"field-control-td"\x3e\r\n          \x3cdiv class\x3d"main-text float-left" data-dojo-attach-point\x3d"lblX"\x3e\x3c/div\x3e\r\n        \x3c/td\x3e\r\n        \x3ctd class\x3d"float-right field-control-td"\x3e\r\n          \x3cselect style\x3d"min-width: 200px" data-dojo-attach-point\x3d"selectX" data-dojo-type\x3d"dijit/form/Select"\x3e\x3c/select\x3e\r\n        \x3c/td\x3e\r\n      \x3c/tr\x3e\r\n\r\n      \x3ctr class\x3d"bottom-border"\x3e\r\n        \x3ctd class\x3d"field-control-td"\x3e\r\n          \x3cdiv class\x3d"main-text float-left" data-dojo-attach-point\x3d"lblY"\x3e\x3c/div\x3e\r\n        \x3c/td\x3e\r\n        \x3ctd class\x3d"float-right field-control-td"\x3e\r\n          \x3cselect style\x3d"min-width: 200px;" data-dojo-attach-point\x3d"selectY" data-dojo-type\x3d"dijit/form/Select"\x3e\x3c/select\x3e\r\n        \x3c/td\x3e\r\n      \x3c/tr\x3e\r\n\r\n    \x3c/tbody\x3e\r\n  \x3c/table\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/Deferred dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/Evented dojo/text!./templates/Coordinates.html dojo/_base/array dijit/form/Select".split(" "),function(g,h,d,k,l,m,n,p,q){return g([k,l,m,n],{baseClass:"cf-coordinates",declaredClass:"CriticalFacilities.Coordinates",templateString:p,_started:null,label:"Coordinates",parent:null,nls:null,map:null,appConfig:null,config:null,fields:[],xField:null,yField:null,theme:"",isDarkTheme:"",
styleColor:"",constructor:function(a){h.mixin(this,a)},postCreate:function(){this.inherited(arguments);this.lblX.innerHTML=this.xField.label+":";this.lblY.innerHTML=this.yField.label+":";this._setFields(this.fields,this.xField,this.yField)},startup:function(){this._started=!0;this._updateAltIndexes()},onShown:function(){this.pageContainer.nextDisabled=!1},validate:function(a,b){var c=new d;"next-view"===a?c.resolve(this._nextView(b)):"back-view"===a?c.resolve(this._backView(b)):this._homeView(b).then(function(a){c.resolve(a)});
return c},_updateAltIndexes:function(){this.pageContainer&&!this._startPageView&&(this._startPageView=this.pageContainer.getViewByTitle("StartPage"),this._locationTypeView=this.pageContainer.getViewByTitle("LocationType"),this._startPageView&&this._locationTypeView?(this.altNextIndex=this._startPageView.index,this.altBackIndex=this._locationTypeView.index):this._startPageView&&(this.altBackIndex=this.altNextIndex=this._startPageView.index))},_nextView:function(a){a.currentView.label===this.label&&
(a=0<this._getResults().fields.length,this.parent._locationMappingComplete=a,this.emit("location-mapping-update",a));return!0},_backView:function(a){a.currentView.label===this.label&&(this.parent._locationMappingComplete=!1,this.emit("location-mapping-update",!1));return!0},_homeView:function(a){var b=new d;this.pageContainer.getViewByTitle("Home").verifyClearSettings(a).then(function(a){b.resolve(a)});return b},_setFields:function(a,b,c){var r=this._getDefaultFieldName(a,b),e=this._getDefaultFieldName(a,
c),f=[{label:this.nls.warningsAndErrors.noValue,value:this.nls.warningsAndErrors.noValue}],d=[{label:this.nls.warningsAndErrors.noValue,value:this.nls.warningsAndErrors.noValue}];q.forEach(a,function(a){f.push({label:a.label,value:a.value,selected:r===a.value});d.push({label:a.label,value:a.value,selected:e===a.value})});this.selectX.addOption(f);this.selectY.addOption(d)},_getDefaultFieldName:function(a,b){b=b.isRecognizedValues;for(var c=0;c<b.length;c++)for(var d=b[c],e=0;e<a.length;e++){var f=
a[e];if(f.value.toString().toUpperCase()===d.toString().toUpperCase())return f.value}},setStyleColor:function(a){this.styleColor=a},updateImageNodes:function(){},updateTheme:function(a){this.theme=a},_getResults:function(){return{type:"xy",fields:this.selectX.value!==this.nls.warningsAndErrors.noValue&&this.selectY.value!==this.nls.warningsAndErrors.noValue?[{targetField:"X",sourceField:this.selectX.value},{targetField:"Y",sourceField:this.selectY.value}]:[]}}})});