// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/Deferred dojo/DeferredList dojo/Evented dojox/data/CsvStore dojo/store/Observable dojo/store/Memory esri/graphicsUtils esri/geometry/webMercatorUtils esri/geometry/Point esri/layers/FeatureLayer esri/tasks/locator esri/tasks/query esri/SpatialReference esri/dijit/PopupTemplate jimu/utils moment/moment".split(" "),function(C,l,f,q,y,D,E,F,G,H,I,t,J,K,z,L,M,A,N){return C([D],{file:null,map:null,spatialReference:null,fsFields:[],duplicateTestFields:[],
geocodeSources:[],duplicateData:[],data:null,editLayer:null,separatorCharacter:null,csvStore:null,storeItems:null,matchedFeatureLayer:null,mappedArrayFields:null,unMatchedFeatureLayer:null,duplicateFeatureLayer:null,addrFieldName:"",xFieldName:"",yFieldName:"",symbol:null,matchFieldPrefix:"MatchField_",_internalFields:[],constructor:function(a){f.mixin(this,a);this.useAddr=!0;this.objectIdField="ObjectID";this.nls=a.nls;this.minScore=90;this._getDuplicateFields(this.fsFields);this.spatialReference=
this.editLayer.spatialReference},_getDuplicateFields:function(a){var b=[];l.forEach(a,function(a){a.duplicate&&b.push(a.name)});this.duplicateTestFields=b},handleCsv:function(){var a=new q;if(this.file&&!this.file.data){var b=new FileReader;b.onload=f.hitch(this,function(){this.data=b.result;this._processCsvData().then(function(b){a.resolve(b)})});b.readAsText(this.file)}return a},_processCsvData:function(){var a=new q;this._convertSources();this._getSeparator();this._getCsvStore().then(function(b){a.resolve(b)});
return a},processForm:function(){this._internalFields=["DestinationOID","matchScore","hasDuplicateUpdates","duplicateState"];this._matchFields=[];var a=new q;this._locateData(this.useAddr).then(f.hitch(this,function(b){for(var c=[],h=[],d=[],k={},e=0,g=0,n=Object.keys(b),r=0;r<n.length;r++){var m={},p=b[n[r]],u=this.storeItems[p.csvIndex];l.forEach(this.fsFields,f.hitch(this,function(a){this.mappedArrayFields.hasOwnProperty(a.name)&&(m[a.name]=this.mappedArrayFields[a.name]?this.csvStore.getValue(u,
this.mappedArrayFields[a.name]):void 0)}));l.forEach(this._currentAddressFields,f.hitch(this,function(a){var b=this.matchFieldPrefix+a.keyField;m[b]="undefined"!==typeof a.value?this.csvStore.getValue(u,a.value):void 0;this._matchFields.push(b)}));p&&p.score>this.minScore?(m.ObjectID=r-e-g,m.matchScore=p.score,c.push({geometry:p.location,attributes:f.clone(m)})):p.isDuplicate?(m.ObjectID=g,m.DestinationOID=p.featureAttributes[this.editLayer.objectIdField],m.matchScore=100,m.hasDuplicateUpdates=!1,
m.duplicateState="no-change",d.push({geometry:p.location,attributes:f.clone(m)}),k[g]=p.featureAttributes,g++):(m.ObjectID=e,m.matchScore=p.score?p.score:0,h.push({geometry:p.location&&p.location.type?p.location:new t(0,0,this.spatialReference),attributes:f.clone(m)}),e++)}this.matchedFeatureLayer=this._initLayer(c,this.file.name.replace(".csv",""));0<d.length&&(this.duplicateFeatureLayer=this._initLayer(d,this.file.name.replace(".csv","")+"_Duplicate"));0<h.length&&(this.unMatchedFeatureLayer=this._initLayer(h,
this.file.name.replace(".csv","")+"_UnMatched"));a.resolve({matchedLayer:this.matchedFeatureLayer,unMatchedLayer:this.unMatchedFeatureLayer,duplicateLayer:this.duplicateFeatureLayer,duplicateLookupList:k})}));return a},_initLayer:function(a,b){a=this._generateFC(a);b=new J(a,{id:b,editable:!0,outFields:["*"]});this._initPopup(b);this.map.addLayers([b]);return b},_initPopup:function(a){var b={title:a.id+": {"+this.labelField+"}"},c=[];l.forEach(a.fields,f.hitch(this,function(a){a.name!==this.objectIdField&&
-1===this._internalFields.indexOf(a.name)&&-1===this._matchFields.indexOf(a.name)&&c.push({fieldName:a.name,visible:!0})}));b.fieldInfos=c;a.infoTemplate=new M(b)},_findDuplicates:function(){var a=new q;this._getAllLayerFeatures(this.editLayer,this.fsFields).then(f.hitch(this,function(b){this.keys=Object.keys(this.mappedArrayFields);this.oidField=this.editLayer.objectIdField;var c=[],h=[],d=this.duplicateTestFields;d&&d.hasOwnProperty("length")&&0<d.length&&l.forEach(this.storeItems,f.hitch(this,
function(a){var b={compareValues:{},fileId:a._csvId,featureId:-1};l.forEach(d,f.hitch(this,function(e){var c=this.mappedArrayFields[e];"undefined"!==typeof c&&(b.compareValues[e]=this.csvStore.getValue(a,c),-1===h.indexOf(e)&&h.push(e))}));0<Object.keys(b.compareValues).length&&c.push(b)}));var k=[];0<c.length&&l.forEach(c,f.hitch(this,function(a){l.forEach(b,f.hitch(this,function(b){var e={};l.forEach(h,f.hitch(this,function(a){e[a]=b.attributes[a]}));if(JSON.stringify(a.compareValues)===JSON.stringify(e)){var c=
b.attributes[this.oidField];-1!==a.featureId?(a.hasMultiDuplicates=!0,"undefined"===typeof a.featureIds?a.featureIds=[c]:a.featureIds.push(c)):(a.featureId=c,a.feature=b,k.push(a))}}))}));a.resolve(k)}));return a},_getAllLayerFeatures:function(a,b){var c=new q,h=[this.editLayer.objectIdField];l.forEach(b,function(a){a.name&&h.push(a.name)});2>h.length&&(h=b);var d=a.maxRecordCount;b=new z;b.where="1\x3d1";a.queryIds(b).then(function(b){var e=[],g,n;if(0<b.length){g=0;for(n=b.length;g<n;g+=d){var k=
new z;k.outFields=h;k.objectIds=b.slice(g,g+d);k.returnGeometry=!0;e.push(a.queryFeatures(k))}(new y(e)).then(f.hitch(this,function(a){if(a){for(var b=[],e=0;e<a.length;e++)a[e][1].features&&b.push.apply(b,a[e][1].features.map(function(a){return{geometry:a.geometry,attributes:a.attributes}}));c.resolve(b)}}))}else c.resolve([])});return c},_locateData:function(a){var b=new q;this._findDuplicates().then(f.hitch(this,function(c){this.duplicateData=c;if(a){var h=f.hitch(this,function(a,b,e){var c=new q,
n=this._geocodeSources[b],d=n.locator;d.outSpatialReference=this.spatialReference;var m=[],k=[],u=0,v,B;v=0;B=a.length;for(;v<B;v+=500){var w=a.slice(v,v+500),t=[];(n.singleEnabled||n.multiEnabled)&&l.forEach(w,f.hitch(this,function(a){var b=a._csvId,c=null,d;a:for(d in this.duplicateData){var h=this.duplicateData[d];if(h.fileId===b){c=f.mixin({},h);delete this.duplicateData[d];break a}}var k={};k.OBJECTID=b;this.useMultiFields&&n.multiEnabled?l.forEach(this.multiFields,f.hitch(this,function(b){this._currentAddressFields=
this.multiFields;if(b.value!==this.nls.noValue){var c=this.csvStore.getValue(a,b.value);k[b.keyField]=c}else k[b.keyField]=void 0})):n.singleEnabled&&this.singleFields[0].value!==this.nls.noValue&&(this._currentAddressFields=this.singleFields,d=this.csvStore.getValue(a,this.singleFields[0].value),"undefined"===typeof d&&(d=typeof d+b),k[n.singleLineFieldName]=d);d=f.mixin({},k);delete d.OBJECTID;d=JSON.stringify(d);null===c?(t.push(k),e[d]={index:u,csvIndex:b,location:{}},u+=1):null!==c&&(e[d]={index:-1,
csvIndex:b,isDuplicate:!0,location:f.mixin({},c.feature.geometry),featureAttributes:c.feature.attributes})}));k.push(d.addressesToLocations({addresses:t,countryCode:n.countryCode,outFields:["ResultID","Score"]}))}var x=Object.keys(e);(new y(k)).then(f.hitch(this,function(d){this.minScore=this._geocodeSources[b]?this._geocodeSources[b].minCandidateScore:90;b+=1;var k=this._geocodeSources.length>b;if(d){var n=this.minScore,g=0;l.forEach(d,f.hitch(this,function(b){b=b[1];l.forEach(b,function(a){a.ResultID=
a.attributes.ResultID});b=F(new G({data:b,idProperty:"ResultID"})).query({},{sort:[{attribute:"ResultID"}]});l.forEach(b,f.hitch(this,function(b){for(var c in x){var d=x[c];if(e[d]&&e[d].index===g){b.attributes.Score<n?k&&(m.push(a[e[d].csvIndex]),delete e[d]):(e[d].location=b.location,e[d].score=b.attributes.Score,delete e[d].index);delete x[c];break}}g+=1}))}));if(k&&0<m.length)h(m,b,e).then(f.hitch(this,function(a){c.resolve(a)}));else return c.resolve(e),c.promise}}));return c});h(this.storeItems,
0,{}).then(f.hitch(this,function(a){b.resolve(a)}))}else this._currentAddressFields=[{keyField:this.xFieldName,label:this.xFieldName,value:this.xFieldName},{keyField:this.yFieldName,label:this.yFieldName,value:this.yFieldName}],this._xyData({storeItems:this.storeItems,csvStore:this.csvStore,xFieldName:this.xFieldName,yFieldName:this.yFieldName,wkid:this.spatialReference.wkid}).then(function(a){b.resolve(a)})}));return b},_xyData:function(a){var b=new q,c=[],h=a.csvStore;l.forEach(a.storeItems,f.hitch(this,
function(b){var d=b._csvId,e=null,g;a:for(g in this.duplicateData){var n=this.duplicateData[g];if(n.fileId===d){e=f.mixin({},n);delete this.duplicateData[g];break a}}var r={};g=h.getAttributes(b);l.forEach(g,function(a){r[a]=h.getValue(b,a)});g=!1;var m,p;null!==e&&e.feature&&e.feature.geometry?(n=e.feature.geometry,g=!0,p=e.feature.attributes):(e=parseFloat(h.getValue(b,a.xFieldName)),m=parseFloat(h.getValue(b,a.yFieldName)),n=this._getGeometry(e,m),m=100);n&&c.push({attributes:r,location:n,csvIndex:d,
score:m,isDuplicate:g,featureAttributes:p})}));b.resolve(c);return b},_getGeometry:function(a,b){var c;"undefined"===typeof c&&(c=/(?=^[-]?\d{1,3}\.)^[-]?\d{1,3}\.\d+|(?=^[-]?\d{4,})|^[-]?\d{1,3}/.exec(a)?!0:!1);if(!isNaN(a)&&!isNaN(b))return a=new t(a,b),c?a=I.geographicToWebMercator(a):a.spatialReference=new L({wkid:this.spatialReference.wkid}),a},_generateFC:function(a){var b={layerDefinition:{geometryType:"esriGeometryPoint",spatialReference:this.editLayer.spatialReference,objectIdField:this.objectIdField,
type:"Feature Layer",drawingInfo:{renderer:{type:"simple",symbol:this.symbol}},fields:[{name:this.objectIdField,alias:this.objectIdField,type:"esriFieldTypeOID"}]},featureSet:{features:a,geometryType:"esriGeometryPoint"}};l.forEach(this.fsFields,f.hitch(this,function(a){b.layerDefinition.fields.push({name:a.name,alias:a.label,type:a.value,editable:!0,domain:null})}));return b},clear:function(){this._removeLayer(this.matchedFeatureLayer);this._removeLayer(this.unMatchedFeatureLayer);this._removeLayer(this.duplicateFeatureLayer);
this.storeItems=this.csvStore=this.separatorCharacter=this.data=this.fsFields=this.file=void 0;this.duplicateData=[];this.mappedArrayFields=this.duplicateFeatureLayer=this.unMatchedFeatureLayer=this.matchedFeatureLayer=void 0;this.useAddr=!0;this.yFieldName=this.xFieldName=this.addrFieldName=""},_removeLayer:function(a){a&&(this.map.removeLayer(a),a.clear())},_getSeparator:function(){var a=this.data.indexOf("\n"),b=f.trim(this.data.substr(0,a)),c=0,h="";l.forEach([",","      ",";","|"],function(a){var d=
b.split(a).length;d>c&&(c=d,h=a)});this.separatorCharacter=h},_getCsvStore:function(){var a=new q;this.csvStore=new E({data:this.data,separator:this.separatorCharacter});this.csvStore.fetch({onComplete:f.hitch(this,function(b){this.storeItems=b;this._fetchFieldsAndUpdateForm(this.storeItems,this.csvStore,this.fsFields).then(function(b){a.resolve(b)})}),onError:function(b){console.error("Error fetching items from CSV store: ",b);a.reject(b)}});return a},_fetchFieldsAndUpdateForm:function(a,b,c){var f=
new q,d=b._attributes,k={};l.forEach(d,function(c){l.forEach(a,function(a){var d=!0,e=!0,f=!0,h=!0,l;k.hasOwnProperty(c)&&(e=k[c].supportsInt,f=k[c].supportsFloat,h=k[c].supportsDate,l=k[c].maxLength,e||f||h||(d=!1));var g=b.getValue(a,c);if(g){a=g.toString().length;var q=N(g);if(d){if(d=h&&q.isValid())if(g)try{d=!isNaN((new Date(g)).getTime())}catch(w){console.error(w),d=!1}else d=-1<[null,void 0,""].indexOf(g)?!0:!1;k[c]={supportsDate:d,supportsInt:!isNaN(parseInt(g,10))&&parseInt(g,10).toString().length===
a&&e,supportsFloat:!isNaN(parseFloat(g))&&parseFloat(g).toString().length===a&&f}}e=k[c];e.maxLength=l;"undefined"===typeof e.maxLength?e.maxLength=a:e.maxLength<a&&(e.maxLength=a)}})});f.resolve({fields:d,fieldTypes:k,fsFields:c});return f},_zoomToData:function(a,b){if(a&&0<a.length)try{var c=H.graphicsExtent(a);b?this.map.setExtent(c.expand(1.9),!0):this.map.setExtent(c,!0)}catch(h){console.log(h.message)}},_convertSources:function(){this.geocodeSources&&0<this.geocodeSources.length&&(this._geocodeSources=
l.map(this.geocodeSources,f.hitch(this,function(a){if(a&&a.url&&"locator"===a.type)return{locator:new K(a.url||""),outFields:["ResultID","Score"],singleLineFieldName:a.singleLineFieldName||"",name:A.stripHTML(a.name||""),placeholder:A.stripHTML(a.placeholder||""),countryCode:a.countryCode||"",addressFields:a.addressFields,singleEnabled:a.singleEnabled||!1,multiEnabled:a.multiEnabled||!1,minCandidateScore:a.minCandidateScore||90}})))}})});